language: ruby
dist: bionic

services:
  - postgresql

cache:
  bundler: true
  directories:
    - $HOME/.nvm/versions/node

rvm:
  - 2.4.5
  - 2.5.7

gemfile: src/ruby/Gemfile

env:
  - "DB=postgresql"


addons:
  firefox: latest
  chrome: stable
  postgresql: "10"

before_install:
  - nvm install v10.16.3
  - node -v
  - npm -v

before_script:
  - cd src/ruby
  - gem install bundler -v 1.17.3
  - bundle install
  - mv config/symmetric-encryption.travis config/symmetric-encryption.yml
  - mv config/database.yml.postgresql config/database.yml
  - bundle exec rails generate symmetric_encryption:new_keys test
  - bundle exec rake fulcrum:setup db:setup
  - firefox -v
  - google-chrome --version
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16

script:
  - "bundle exec rails t"
