language: ruby

# This is going to enable build on VMs instead of containers
sudo: required

cache:
  bundler: true
  directories:
    - $HOME/.nvm/versions/node

rvm:
  - 2.2.5
  - 2.3.1

env:
  - "DB=postgresql"

before_install:
  - nvm install v6.7.0
  - node -v
  - npm -v
  - npm install -g phantomjs-prebuilt
  - phantomjs -v
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

before_script:
  - phantomjs -v
  - "bundle exec rake --trace fulcrum:setup db:setup"

script:
  - "bundle exec rake travis"
