language: ruby

# This is going to enable build on VMs instead of containers
sudo: required
dist: trusty

cache:
  bundler: true
  directories:
    - $HOME/.nvm/versions/node

rvm:
  - 2.2.5
  - 2.3.1

env:
  - "DB=postgresql"

before_install:
  - nvm install v6.7.0
  - node -v
  - npm -v
  - npm install -g phantomjs-prebuilt
  - phantomjs -v

install:
  - mv config/symmetric-encryption.travis config/symmetric-encryption.yml
  - bundle install
  - bundle exec rails generate symmetric_encryption:new_keys test

before_script:
  - phantomjs -v
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "bundle exec rake --trace fulcrum:setup db:setup"

script:
  - "bundle exec rake travis"
