language: ruby

# This is going to enable build on VMs instead of containers
sudo: required
dist: trusty

cache:
  bundler: true
  directories:
    - $HOME/.nvm/versions/node

rvm:
  - 2.4.5
  - 2.5.7

env:
  - "DB=postgresql"

addons:
  firefox: 45.0esr

before_install:
  - nvm install v6.7.0
  - node -v
  - npm -v
  - npm install -g phantomjs-prebuilt
  - phantomjs -v

before_script:
  - cd src/ruby
  - gem install bundler -v 1.17.3
  - bundle install
  - mv config/symmetric-encryption.travis config/symmetric-encryption.yml
  - mv config/database.yml.postgresql config/database.yml
  - bundle exec rails generate symmetric_encryption:new_keys test
  - bundle exec rake fulcrum:setup db:setup
  - phantomjs -v
  - firefox -v
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16

script:
  - "bundle exec rake travis"
