source 'http://rubygems.org'

gem 'rails', '5.0.7.2'
gem 'sass-rails', '5.0.5'
gem 'uglifier', '4.1.20'
gem 'jquery-rails', '4.3.5'
gem 'ejs'
gem 'compass-rails'
gem 'devise', '4.7.1'
gem 'transitions', '0.1.9', require: ['transitions', 'active_record/transitions']
gem 'rails-i18n'
gem 'configuration'
gem 'rails-observers', '0.1.5'
gem 'jquery-ui-rails'
gem 'rubyzip', '1.3.0'
gem "ffi", '1.9.25'
gem "nokogiri", "1.10.4"

gem 'pg'

# Symmetric Encryption using OpenSSL
gem 'symmetric-encryption', '3.8.3'

# For assets compilation and migration on remote servers
gem 'therubyracer', '0.12.3', platforms: :ruby

group :development do
  gem 'letter_opener'
end

group :development, :test do
  gem 'pry'
  gem 'byebug'
  gem 'rspec-rails'
  gem 'rspec-its'
  gem 'rspec-activemodel-mocks'
  gem 'factory_girl_rails'
  gem 'jasmine-rails'
  gem 'sinon-rails'
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'poltergeist'
  gem 'database_cleaner'
  # gem 'quiet_assets'
end

group :production do
  gem 'unicorn', '5.1.0'
end
