source 'http://rubygems.org'

gem 'rails', '5.0.7.2'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '4.1.20'
gem 'jquery-rails', '4.3.5'
gem 'ejs'
gem 'compass-rails'
gem 'devise', '4.7.1'
gem 'transitions', '0.1.9', require: ['transitions', 'active_record/transitions']
gem 'rails-i18n'
gem 'configuration'
gem 'rails-observers', '0.1.5'
gem 'jquery-ui-rails'
gem 'rubyzip', '1.3.0'
gem "ffi", '1.9.25'
gem "nokogiri", "1.13.2"
gem 'pg'

# Symmetric Encryption using OpenSSL
gem 'symmetric-encryption', '3.8.3'

# For assets compilation and migration on remote servers
gem 'therubyracer', '0.12.3', platforms: :ruby

group :development do
  gem 'letter_opener'
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '~> 3.0.5'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :development, :test do
  gem 'byebug'
end

group :production do
  gem 'unicorn', '5.1.0'
end
