source 'http://rubygems.org'

gem 'rails', '4.2.11.1'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '4.1.20'
gem 'jquery-rails', '3.1.5'
gem 'ejs'
gem 'compass-rails'
gem 'devise', '4.7.1'
gem 'transitions', '0.1.9', require: ['transitions', 'active_record/transitions']
gem 'rails-i18n'
gem 'configuration'
gem 'rails-observers', '~> 0.1.2'
gem 'jquery-ui-rails'
gem 'rubyzip', '1.3.0'
gem "ffi", '1.9.25'

gem 'pg'

# Symmetric Encryption using OpenSSL
gem 'symmetric-encryption', '3.8.3'

# For assets compilation and migration on remote servers
gem 'therubyracer', '0.12.3', platforms: :ruby

group :development do
  gem 'letter_opener'
end

group :development, :test do
  gem 'pry'
  gem 'byebug'
  gem 'rspec-rails', '3.4.2'
  gem 'rspec-its', '1.2.0'
  gem 'rspec-activemodel-mocks', '1.0.3'
  gem 'factory_girl_rails', '4.7.0'
  gem 'jasmine-rails', '0.14.1'
  gem 'sinon-rails', '1.15.0'
  gem 'capybara', '2.10.1'
  gem 'selenium-webdriver','2.53.4'
  gem 'poltergeist','1.11.0'
  gem 'database_cleaner'
  gem 'quiet_assets'
end

group :production do
  gem 'unicorn', '5.1.0'
end
